simulation_rate: 100.0 # Hz
clock_rate: 100.0 # Hz
realtime_factor: 1.0 # [-]

g: 9.81 # [ms^-2]

iterate_without_input: true

input_timeout: 1.0 # [s]

sensors:
  lidar:
    enabled: true
    rate: 10.0 # [Hz]
    horizontal_fov: 360.0 # [deg]
    vertical_fov: 45.0 # [deg]
    horizontal_rays: 128
    vertical_rays: 32
    offset_x: 0.0 # [m]
    offset_y: 0.0 # [m]
    offset_z: 6.0 # [m]
    rotation_pitch: 0.0 # [deg]
    rotation_roll: 90.0 # [deg]
    rotation_yaw: 0.0 # [deg]
    beam_length: 1000.0 # [m]
  lidar_seg:
    enabled: false
    rate: 10.0 # [Hz]
  rgb:
    enabled: true
    rate: 10.0 # [Hz]
    width: 640
    height: 480
    fov: 90
    offset_x: 14.9
    offset_y: 0.0
    offset_z: 0.0
    rotation_pitch: 0.0
    rotation_yaw: 0.0
    rotation_roll: 0.0

  depth:
    enabled: false
    rate: 10.0 # [Hz]
  seg:
    enabled: false
    rate: 5.0 # [Hz]
  color_depth:
    enabled: false
    rate: 5.0 # [Hz]

frames:
  world:
    name: "simulator_origin"
    prefix_with_uav_name: false
  fcu:
    name: "fcu"
    publish_tf: false
  rangefinder:
    name: "garmin"
    publish_tf: true

# randomization of the initial conditions around the desired spawn point
randomization:

  enabled: false

  bounds:
    x: 15.0
    y: 15.0
    z: 15.0

ground:
  enabled: true
  z: 0.0 # [m]

# * when enabled, this will place a temporary patch of ground just under the spawn location
# * this patch will disappear after the total_thrust > 0.9*hover_thrust
individual_takeoff_platform:
  enabled: false
