simulation_rate: 250
clock_rate: 250
realtime_factor: 1.0

iterate_without_input: true

individual_takeoff_platform:
  enabled: false

frames:
  world:
    name: "simulator_origin"
    prefix_with_uav_name: false
  fcu:
    name: "fcu"
    publish_tf: false
  rangefinder:
    name: "garmin"
    publish_tf: true

uav_names: [
  "uav1",
  "uav2",
]

uav1:
  type: "x500"
  spawn:
    x: 0.0 #10.0
    y: 0.0 #15.0
    z: 2.0
    heading: 0


uav2:
  type: "x500"
  spawn:
    x: 0.0 #10.0
    y: 6.0 #15.0
    z: 2.0
    heading: 0
